### ISSUE TITLE
Cloudflare Browser Check 

### ISSUE THREAD

**Issue by loco4384** [Omega-Slender/ITSNOTPOEVER-ST-EDITED#11]
Poe has put a bot check on the site so bots cannot be accessed via npm.
![imagen_2023-08-04_110351458](https://github.com/Omega-Slender/ITSNOTPOEVER-ST-EDITED/assets/136152582/5d59b5f9-0764-4ad5-b550-1b42c083c49d)

**Comment by slenderblak** [comment]
rip

**Comment by Athern1** [comment]
Yeah, any fix for this? i can access it yesterday and pass the captcha. But now i'm stuck

**Comment by Omega-Slender** [comment]
Download the latest version because it is already fixed.

**Comment by HarmOnGitHub** [comment]
For anyone still using the old version with the cookie login, I've found that using a vpn when launching start.bat bypasses the cloudflare page 9/10 times.
